plugins {
	id 'multiloader-loader'
	id 'net.fabricmc.fabric-loom'
}

final def includeModMenu = project.hasProperty("launch_with_modmenu") && project.launch_with_modmenu.toBoolean()
final def includeXaero = project.hasProperty("launch_with_xaero_worldmap") && project.launch_with_xaero_worldmap.toBoolean()
final def includeIrisAndSodium = project.hasProperty("launch_with_iris_and_sodium") && project.launch_with_iris_and_sodium.toBoolean()

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
	maven {
		name = "Terraformers"
		url = "https://maven.terraformersmc.com/"
	}
}

dependencies {
	minecraft("com.mojang:minecraft:${minecraft_version}")
	implementation("net.fabricmc:fabric-loader:${fabric_loader_version}")

	implementation("net.fabricmc.fabric-api:fabric-api:${fabric_version}")

	if (includeModMenu) {
		implementation("com.terraformersmc:modmenu:${project.modmenu_version}")
	} else {
		compileOnly("com.terraformersmc:modmenu:${project.modmenu_version}")
	}

	if (includeXaero) {
		implementation "xaero.map:xaeroworldmap-fabric-${project.minecraft_version}:${project.xaero_worldmap_version}"
	} else {
		compileOnly "xaero.map:xaeroworldmap-fabric-${project.minecraft_version}:${project.xaero_worldmap_version}"
	}

	compileOnly "info.journeymap:journeymap-api-fabric:${project.journeymap_api_version}"

	if (includeIrisAndSodium) {
		implementation "maven.modrinth:iris:${project.iris_shader_version}-fabric"
	} else {
		compileOnly "maven.modrinth:iris:${project.iris_shader_version}-fabric"
	}

	if (includeIrisAndSodium) {
		implementation "maven.modrinth:sodium:mc${project.sodium_version}-fabric"
	} else {
		compileOnly "maven.modrinth:sodium:mc${project.sodium_version}-fabric"
	}
}

loom {
	def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
	if (aw.exists()) {
		accessWidenerPath.set(aw)
	}
	runs {
		client {
			client()
			setConfigName('Fabric Client')
			ideConfigGenerated(true)
			runDir('runs/client')
		}
	}
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'modCompileClasspath'].each { variant ->
	configurations.named(variant) {
		attributes {
			attribute(loaderAttribute, 'fabric')
		}
	}
}
sourceSets.configureEach {
	[it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
		configurations.named(variant) {
			attributes {
				attribute(loaderAttribute, 'fabric')
			}
		}
	}
}
