# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
minecraft_dependency=~26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.1
maven_group=me.Azz_9
archives_base_name=screenshot-utilities

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.153.0+26.2
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu_version=20.0.0-beta.4
launch_with_modmenu=true
# https://chocolateminecraft.com/maven/xaero/map/
xaero_worldmap_version=1.41.3
launch_with_xaero_worldmap=true
# https://maven.blamejared.com/info/journeymap/journeymap-api-fabric/
journeymap_api_version=26.2-2.0.0

iris_shader_version=1.10.9